name: Build

on:
  workflow_dispatch:
  push:

env:
  node_version: 20

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          node-version: ${{env.node_version}}
      - run: npm ci
      - run: npm test
      - run: npm run build
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@main
        with:
          name: dist
          path: dist
      - name: Set commit status
        if : always()
        uses: actions/github-script@main
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.sha,
              state: "${{ job.status }}",
            });
