name: Build

on:
  workflow_dispatch:
  push:

env:
  node_version: 21

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        command:
          - node --loader ts-node/esm --test-reporter=spec --test
          - node --import tsx --test-reporter=spec --test
        files:
          - ./__tests__/**/*.test.ts
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          node-version: ${{env.node_version}}
      - run: npm ci
      - run: ${{ matrix.command }} ${{ matrix.files }}
      - run: npm run build
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@main
        with:
          name: dist
          path: dist
