# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Publish

on:
  workflow_dispatch:
  release:
    types: [created]

env:
  node_version: 21

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        command:
          - node --loader ts-node/esm --test-reporter=spec --test
          - node --import tsx --test-reporter=spec --test
        files:
          - ./__tests__/**/*.test.ts
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          node-version: ${{env.node_version}}
      - run: npm ci
      - run: ${{ matrix.command }} ${{ matrix.files }}

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          node-version: ${{env.node_version}}
      - run: npm ci
      - run: npm run build
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@main
        with:
          name: dist
          path: dist

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          node-version: ${{env.node_version}}
          registry-url: https://npm.pkg.github.com/
      - run: npm ci
      - name: Download a Build Artifact
        uses: actions/download-artifact@main
        with:
          name: dist
          path: dist
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          node-version: ${{env.node_version}}
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - name: Download a Build Artifact
        uses: actions/download-artifact@main
        with:
          name: dist
          path: dist
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
