name: Test and Build

on:
  workflow_dispatch:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node_version:
          - 18
          - 19
          - 20
          - 21
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          node-version: ${{ matrix.node_version }}
      - run: npm ci
      - run: npm run test

  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node_version:
          - 18
          - 19
          - 20
          - 21
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          node-version: ${{ matrix.node_version }}
      - run: npm ci
      - run: npm run build
