name: Test and Build

on:
  workflow_dispatch:
  push:

env:
  test_pattern: ./__tests__/**/*.test.ts

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test_command:
          - tsx --test ${{ github.env.test_pattern }}"
          - node --loader ts-node/esm --test ${{ github.env.test_pattern }}"
          - node --loader @esbuild-kit/esm-loader --test -r esbuild-register ${{ github.env.test_pattern }}"
          - node --loader @esbuild-kit/esm-loader --test  ${{ github.env.test_pattern }}"
          - node --import tsx --test ${{ github.env.test_pattern }}"
          - glob ${{ github.env.test_pattern }} -c 'tsx --test'"
          - glob ${{ github.env.test_pattern }} -c 'node --import tsx --test'"
        node_version:
          - 18
          - 19
          - 20
          - 21
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          node-version: ${{ matrix.node_version }}
      - run: npm ci
      - run: npx -y ${{ matrix.test_command }}

  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node_version:
          - 18
          - 19
          - 20
          - 21
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          node-version: ${{ matrix.node_version }}
      - run: npm ci
      - run: npm run build
