name: Test and Build

on:
  workflow_dispatch:
  push:


jobs:
  setup:
    env:
      TEST_PATTERN: ./__tests__/**/*.test.ts
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout to repository
        uses: actions/checkout@main
        with:
          sparse-checkout: .github/fixtures
      - name: Set matrix data
        env:
          FILE: .github/fixtures/matrix.json
        id: set-matrix
        run: echo "matrix=$(jq -c . < $FILE)" >> $GITHUB_OUTPUT

  test:
    runs-on: ubuntu-latest
    needs: setup
    strategy:
      fail-fast: false
      matrix:
        fixture: ${{ fromJson(needs.setup.outputs.matrix).fixtures }}
        node_version:
          - 18
          - 19
          - 20
          - 21
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          node-version: ${{ matrix.node_version }}
      - run: npm ci
      - run: ${{ matrix.fixture }}

  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node_version:
          - 18
          - 19
          - 20
          - 21
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          node-version: ${{ matrix.node_version }}
      - run: npm ci
      - run: npm run build
