name: Test and Build

on:
  workflow_dispatch:
  push:

env:
  TEST_PATTERN: ./__tests__/**/*.test.ts

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node_version:
          # - 18
          # - 19
          # - 20
          - 21
        fixture:
          - yarn test
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          node-version: ${{ matrix.node_version }}
      - run: npm install -g yarn
      - run: yarn install
      - run: ${{ matrix.fixture }}

  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node_version:
          - 18
          - 19
          - 20
          - 21
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          node-version: ${{ matrix.node_version }}
      - run: npm install -g yarn
      - run: yarn install
      - run: yarn build
