name: Test and Build

on:
  workflow_dispatch:
  push:

env:
  TEST_PATTERN: ./__tests__/**/*.test.ts

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node_version:
          # - 18
          # - 19
          # - 20
          - 21
        fixture:
          - yarn tsx --test $TEST_PATTERN
          - yarn node --loader ts-node/esm --test $TEST_PATTERN
          - yarn node --loader @esbuild-kit/esm-loader --test -r esbuild-register $TEST_PATTERN
          - yarn node --loader @esbuild-kit/esm-loader --test  $TEST_PATTERN
          - yarn node --import tsx --test $TEST_PATTERN
          - yarn glob $TEST_PATTERN -c 'tsx --test'
          - yarn glob $TEST_PATTERN -c 'node --import tsx --test'
          - yarn dlx tsx --test $TEST_PATTERN
          - yarn dlx node --loader ts-node/esm --test $TEST_PATTERN
          - yarn dlx node --loader @esbuild-kit/esm-loader --test -r esbuild-register $TEST_PATTERN
          - yarn dlx node --loader @esbuild-kit/esm-loader --test  $TEST_PATTERN
          - yarn dlx node --import tsx --test $TEST_PATTERN
          - yarn dlx glob $TEST_PATTERN -c 'tsx --test'
          - yarn dlx glob $TEST_PATTERN -c 'node --import tsx --test'
          - node --loader ts-node/esm --test $TEST_PATTERN
          - node --loader @esbuild-kit/esm-loader --test -r esbuild-register $TEST_PATTERN
          - node --loader @esbuild-kit/esm-loader --test  $TEST_PATTERN
          - node --import tsx --test $TEST_PATTERN
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          node-version: ${{ matrix.node_version }}
      - run: npm install -g yarn
      - run: yarn install
      - run: ${{ matrix.fixture }}

  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node_version:
          - 18
          - 19
          - 20
          - 21
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          node-version: ${{ matrix.node_version }}
      - run: npm install -g yarn
      - run: yarn install
      - run: yarn build
